# This is the configuration used to check the rubocop source code.

# inherit_from: .rubocop_todo.yml
# require: rubocop/cop/internal_affairs

AllCops:
  Exclude:
    - '/**/*.rb'
    - 'vendor/**/*'
    - 'spec/fixtures/**/*'
    - 'tmp/**/*'
    - 'dev/'
    - '.dotfiles/**/*'
    - '.rbenv/**/*'
    - '.gem/**/*'
    - '.bundle/**/*'
    - '.escaped_colors.rb'
    - '.unescaped_colors.rb'
    - '.gemrc'
    - '.pryrc'

  TargetRubyVersion: 2.0

Style/FrozenStringLiteralComment:
  EnforcedStyle: always

Layout/EndOfLine:
  EnforcedStyle: lf

Layout/IndentHeredoc:
  EnforcedStyle: powerpack

Lint/AmbiguousBlockAssociation:
  Exclude:
    - 'spec/**/*.rb'
    - .dotfiles/**/*.rb

Lint/UselessAccessModifier:
  MethodCreatingMethods:
    - 'def_matcher'
    - 'def_node_matcher'

# Lint/BooleanSymbol:
  # Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'Rakefile'
    - '**/*.rake'
    - 'spec/**/*.rb'
    - .dotfiles/**/*.rb

Metrics/ModuleLength:
  Exclude:
    - 'spec/**/*.rb'
    - .dotfiles/**/*.rb

Performance/Caller:
  Exclude:
    - .dotfiles/**/*.rb
